name: Merge Staging to QA

on:
  push:
    branches:
      - staging

jobs:
  merge_to_qa:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Merge Staging to QA
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "thawzinmyo"
          git config user.email "thawzinmyo@yomafleet.com"
          git checkout qa
          git pull origin qa
          git merge staging
          git push origin qa






































# name: Merge Staging to QA

# on:
#   pull_request:
#     types:
#       - closed

# jobs:
#   merge_staging_to_feature_qa:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Check out code
#         uses: actions/checkout@v2

#       - name: Merge Staging to QA
#         if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'staging'
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         run: |
#           git config user.name "thawzinmyo"
#           git config user.email "thawzinmyo@yomafleet.com"
#           git checkout staging
#           git pull origin staging
#           git checkout qa
#           git merge staging
#           git push origin qa